### ISSUE TITLE
Statusuppdatering och framtida fixar

### ISSUE THREAD

**Issue by AlexJaxgaard** [BenBrew/Explore-Style#6]
Onsdag 20/10-2021:

Efter kraschen av WordPress och opålitlig host kommer fortsatta felsökningar att pågå, se #4 för fler detaljer och mer information gällande det. 

Om byte av host inte löser problemet kommer källkoden noggrannt att undersökas för att effektivisera sidan, kanske är det en bild som har en för hög upplösning eller att det kommer in för måna queries till databas, men i nuläget är det högst osannolikt.

Menyer håller på att byggas upp igen, och skapandet av fler sidor på Wordpress avvaktas med tills det att nya hosten är färdig och all källkod är inspekterad och verifierad. 

Efter ominstallation verkar sidan köras felfritt, men det uppstår lagg väldigt ofta.
--

**Comment by BenBrew** [comment]
Statusuppdatering stängs då andra individuella issues är skapade för varje problem.
