### ISSUE TITLE
Byte av host

### ISSUE THREAD

**Issue by AlexJaxgaard** [BenBrew/Explore-Style#7]
Detta issue/enhancement kan kopplas till #5 #6 

På grund av den opålitliga host som sidan för nuvarande ligger på kommer ett byte ske inom kort. 

Just nu så ser den framtida hosten ut att vara "Misshosting", men detta kan ändras med tiden pga bl.a prisskillnad. 

Anledningen till hostbyte är eftersom att sidan ej upplevs som "snabb" nog, och för många användare på flera olika enheter har långsam anslutning varit ett problem. På grund av detta kommer slutprodukten att bli försenad, då skapandet av sidor inom WordPress ändå inte kommer att vara aktuellt på nuvarande host på grund av bytet. 

Det är inte bara hosten som upplevs gå långsamt. Även Wordpress kontrollpanel är väldigt långsam och kan påverka t.ex släpp av nya produkter om inte den undersöks och effektiviseras. 

Dessutom så måste sidan undersökas för eventuella fel i källkod som kan påverka huruvida effektiv sidan är, eftersom att detta inte bara påverkar sidan för slutanvändare, utan även för andra företag som kan komma att använda temat.

**Comment by BenBrew** [comment]
Uppdatering torsdag 21/10-21 13:01:

Sidan ska nu vara igång med full funktionalitet. Ärendet avslutas och issue stängs.

--
